paths:
  parquet_treino_unificado: data/parquet/parquet_treino_unificado.parquet
  candidatos_parquet_dir: data/parquet/applicants
  prospects_parquet_dir: data/parquet/prospects
  vagas_parquet_dir: data/parquet/vagas

features:
  target_column: "y"

train:
  test_size: 0.2
  random_state: 42

model:
  random_forest:
    n_estimators: 100
    random_state: 42
