# Hiperparâmetros para os modelos
random_forest:
  n_estimators: 200
  max_depth: 9
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: auto
  class_weight: balanced
  # adicione aqui mais parâmetros se quiser
