name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  IMAGE_NAME:    ${{ env.ECR_REGISTRY }}:latest

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: projeto_datathon_brunag
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt pytest pyarrow

      - name: Run unit tests
        working-directory: projeto_datathon_brunag
        run: pytest tests/ -q

  build-and-push:
    name: Build & Push Docker Image
    needs: unit-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region:            ${{ secrets.AWS_REGION }}
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        working-directory: projeto_datathon_brunag
        uses: docker/build-push-action@v2
        with:
          context: .
          push:    true
          tags:    |
            ${{ env.IMAGE_NAME }}

  deploy:
    name: Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Make deploy.sh executable
        working-directory: projeto_datathon_brunag
        run: chmod +x deploy.sh

      - name: Deploy to EC2
        working-directory: projeto_datathon_brunag
        env:
          IMAGE_NAME:     ${{ env.IMAGE_NAME }}
          REGISTRY_TYPE:  ecr
          AWS_REGION:     ${{ secrets.AWS_REGION }}
          EC2_USER:       ${{ secrets.EC2_USER }}
          EC2_HOST:       ${{ secrets.EC2_HOST }}
          EC2_KEY_PATH:   ~/.ssh/id_rsa
          CONTAINER_NAME: datathon-api
          REMOTE_PORT:    80
          CONTAINER_PORT: 8000
        run: ./deploy.sh
