name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Prepare test environment
        working-directory: projeto_datathon_brunag
        run: |
          # Cria pasta para salvar o modelo
          mkdir -p model
          echo "PATH_MODEL=$(pwd)/model/modelo_classificador.pkl" >> $GITHUB_ENV

          # Cria pastas vazias para os dados parquet do treino
          mkdir -p data/parquet/applicants
          mkdir -p data/parquet/prospects
          mkdir -p data/parquet/vagas

          # Exporta as variáveis de ambiente usadas pelo run_train.py
          echo "PATH_PARQUET_APPLICANTS=$(pwd)/data/parquet/applicants"  >> $GITHUB_ENV
          echo "PATH_PARQUET_PROSPECTS=$(pwd)/data/parquet/prospects"    >> $GITHUB_ENV
          echo "PATH_PARQUET_VAGAS=$(pwd)/data/parquet/vagas"            >> $GITHUB_ENV

      - name: Install runtime dependencies
        working-directory: projeto_datathon_brunag
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Install dev dependencies
        working-directory: projeto_datathon_brunag
        run: pip install pytest

      - name: Run tests
        working-directory: projeto_datathon_brunag
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Build Docker image
        working-directory: projeto_datathon_brunag
        run: docker build -t seu-usuario/projeto-datathon:latest .
