name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]  # agora é string, não float

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}

      - name: Prepare test environment
        working-directory: projeto_datathon_brunag
        run: |
          mkdir -p model
          echo "PATH_MODEL=$(pwd)/model/pipeline.joblib" >> $GITHUB_ENV
          mkdir -p data/parquet/{applicants,prospects,vagas}
          echo "PATH_PARQUET_APPLICANTS=$(pwd)/data/parquet/applicants"  >> $GITHUB_ENV
          echo "PATH_PARQUET_PROSPECTS=$(pwd)/data/parquet/prospects"    >> $GITHUB_ENV
          echo "PATH_PARQUET_VAGAS=$(pwd)/data/parquet/vagas"            >> $GITHUB_ENV

      - name: Install dependencies
        working-directory: projeto_datathon_brunag
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt pytest

      - name: Run all tests
        working-directory: projeto_datathon_brunag
        run: pytest tests/ --maxfail=1 --disable-warnings -q

      - name: Lint with flake8
        working-directory: projeto_datathon_brunag
        run: |
          pip install flake8
          flake8 .

      - name: Build Docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v4
        with:
          context: projeto_datathon_brunag
          file:    projeto_datathon_brunag/Dockerfile
          push:    false
          tags:    seu-usuario/projeto-datathon:latest
          cache-from: type=registry,ref=seu-usuario/projeto-datathon:latest
          cache-to:   type=inline
